# 1.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

## Часть 1 (19 баллов)

1) Импортировать numpy и написать версию (1 балл)

In [2]:
import numpy

In [217]:
print(numpy.__version__)

1.17.2


2) Создать нулевой вектор размера 10 (1 балл)

In [216]:
print(numpy.zeros((10), dtype = numpy.int16))

[0 0 0 0 0 0 0 0 0 0]


3) Создать вектор заполненный 7-ами размера 7 (2 балла)


In [215]:
print(7 * numpy.ones((7), dtype = numpy.int16))

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100 включительно (2 балла)

In [214]:
print(numpy.arange(10, 101, 2))

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд (4 балла)

In [191]:
a = numpy.random.randint(0, 10, 10)
print(a)
print(a[::-1])

[6 3 8 8 0 6 4 2 7 4]
[4 7 2 4 6 0 8 8 3 6]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9 (4 балла)

In [213]:
print(numpy.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх. (5 баллов)

In [212]:
print(numpy.eye(4, k=1, dtype = numpy.int16))

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


## Часть 2 (26 баллов)

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки. (2 балла)

In [194]:
a = 7 * numpy.ones((4,4), dtype = numpy.int16)
numpy.fill_diagonal(a, numpy.arange(1, 5))
print(a)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках. (2 балла)

In [211]:
print(numpy.tile(numpy.arange(5), 5).reshape(5, 5))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки (3 балла)

In [210]:
a = numpy.random.randint(0, 10, (10, 10))
print(a, "\n")
b = (numpy.sum(a, axis = 1) / 10).reshape((10, 1))
print(b, "\n")
print(a - b)

[[9 6 1 5 8 8 6 2 7 7]
 [5 4 3 1 0 8 7 4 8 3]
 [7 3 7 8 2 5 9 0 1 5]
 [2 7 3 3 7 8 9 7 9 3]
 [4 4 7 4 6 0 7 0 2 2]
 [0 8 0 1 8 5 0 3 9 2]
 [4 1 6 1 3 3 1 9 4 3]
 [2 0 4 8 3 1 1 6 9 4]
 [6 9 1 8 3 2 8 6 6 8]
 [8 1 7 5 4 1 5 0 2 5]] 

[[5.9]
 [4.3]
 [4.7]
 [5.8]
 [3.6]
 [3.6]
 [3.5]
 [3.8]
 [5.7]
 [3.8]] 

[[ 3.1  0.1 -4.9 -0.9  2.1  2.1  0.1 -3.9  1.1  1.1]
 [ 0.7 -0.3 -1.3 -3.3 -4.3  3.7  2.7 -0.3  3.7 -1.3]
 [ 2.3 -1.7  2.3  3.3 -2.7  0.3  4.3 -4.7 -3.7  0.3]
 [-3.8  1.2 -2.8 -2.8  1.2  2.2  3.2  1.2  3.2 -2.8]
 [ 0.4  0.4  3.4  0.4  2.4 -3.6  3.4 -3.6 -1.6 -1.6]
 [-3.6  4.4 -3.6 -2.6  4.4  1.4 -3.6 -0.6  5.4 -1.6]
 [ 0.5 -2.5  2.5 -2.5 -0.5 -0.5 -2.5  5.5  0.5 -0.5]
 [-1.8 -3.8  0.2  4.2 -0.8 -2.8 -2.8  2.2  5.2  0.2]
 [ 0.3  3.3 -4.7  2.3 -2.7 -3.7  2.3  0.3  0.3  2.3]
 [ 4.2 -2.8  3.2  1.2  0.2 -2.8  1.2 -3.8 -1.8  1.2]]


4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца (4 балла)

In [206]:
a = numpy.random.randint(0, 10, (10,10), dtype = numpy.int16)
print(a, "\n")
b = numpy.median(a, axis = 0)
print(b, "\n")
print(a - b)

[[6 1 2 0 5 1 2 7 2 2]
 [5 2 4 2 0 4 5 7 4 1]
 [2 5 0 4 2 2 2 2 8 8]
 [7 2 6 7 3 7 5 0 5 0]
 [0 8 8 5 2 8 2 9 9 7]
 [7 4 3 8 2 2 1 1 5 0]
 [1 6 4 3 1 6 8 3 3 6]
 [0 3 8 8 4 8 2 3 0 2]
 [0 3 9 7 3 4 2 3 4 7]
 [9 6 0 9 4 9 8 8 7 2]] 

[3.5 3.5 4.  6.  2.5 5.  2.  3.  4.5 2. ] 

[[ 2.5 -2.5 -2.  -6.   2.5 -4.   0.   4.  -2.5  0. ]
 [ 1.5 -1.5  0.  -4.  -2.5 -1.   3.   4.  -0.5 -1. ]
 [-1.5  1.5 -4.  -2.  -0.5 -3.   0.  -1.   3.5  6. ]
 [ 3.5 -1.5  2.   1.   0.5  2.   3.  -3.   0.5 -2. ]
 [-3.5  4.5  4.  -1.  -0.5  3.   0.   6.   4.5  5. ]
 [ 3.5  0.5 -1.   2.  -0.5 -3.  -1.  -2.   0.5 -2. ]
 [-2.5  2.5  0.  -3.  -1.5  1.   6.   0.  -1.5  4. ]
 [-3.5 -0.5  4.   2.   1.5  3.   0.   0.  -4.5  0. ]
 [-3.5 -0.5  5.   1.   0.5 -1.   0.   0.  -0.5  5. ]
 [ 5.5  2.5 -4.   3.   1.5  4.   6.   5.   2.5  0. ]]


5) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7. (4 балла) 

In [198]:
a = numpy.random.randint(0,10,(5,5), dtype = numpy.int16)
a = numpy.hstack((a, numpy.max(a, axis = 1).reshape(5,1)))
a = numpy.hstack((a, numpy.min(a, axis = 1).reshape(5,1)))
print(a)


[[4 5 9 9 1 9 1]
 [5 2 9 9 8 9 2]
 [2 1 7 9 5 9 1]
 [3 4 4 6 5 6 3]
 [7 5 2 0 7 7 0]]


6) Вектор чисел от 1 до 50 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  (6 баллов)

In [6]:
a = numpy.arange(1, 51)
print(a, "\n")
b = numpy.matrix(a[numpy.arange(1, 50, 2)]).reshape((5,5))
print(b, "\n")
c = numpy.matrix(a[numpy.arange(0, 50, 2)]).reshape((5,5))
print(c, "\n")
mul = b * c
print(mul, "\n")
inv = numpy.linalg.inv(mul)
print(inv)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50] 

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]] 

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]] 

[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]] 

[[ 2.33534705e+14  7.54735942e+14 -1.12919844e+15 -9.39949760e+14
   1.08087756e+15]
 [ 6.91792369e+12 -1.45842694e+13  4.39804651e+12  7.28502043e+12
  -4.01672122e+12]
 [-4.73799516e+14 -1.49342919e+15  2.25179981e+15  1.87188600e+15
  -2.15645711e+15]
 [-7.29355756e+12  1.16674155e+13  0.00000000e+00 -5.82801634e+12
   1.45415837e+12]
 [ 2.40640445e+14  7.41610099e+14 -1.12699942e+15 -9.33393242e+14
   1.07814212e+15]]


7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. (5 баллов)

In [200]:
a = numpy.array([0, 1])
print(numpy.matrix(a[(1 + numpy.matrix([(-1)**(i + j) for i in range(8) for j in range(8)])//2).reshape(8,8)]))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
